name: 'Push to changelog'
description: 'Adds commits to a changelog file'
inputs:
  token:
    description: 'GitHub token'
    required: true
  filePath:
    description: 'Path to your changelog'
  prefix:
    description: 'What commits need to start with to be added to the changelog'
runs:
  using: 'node20'
  main: 'dist/index.js'
